### GET ALL USERS
GET http://localhost:4000/api/users

### GET USER INFO
GET http://localhost:4000/api/users/auth

### REGISTER USER
POST http://localhost:4000/api/users/register
Content-Type: application/json

 {
    "username": "cat-9@mail.com",
    "password": "hey-hello"
 }

### LOGIN USER
POST http://localhost:4000/api/users/login
Content-Type: application/json

 {
    "username": "cat-03@mail.com",
    "password": "hey-hello"
 }

### UPDATE USER
PUT http://localhost:4000/api/users/6631726c93081557518a7e3b
Content-Type: application/json

 { 
    "username": "cat-updated1@mail.com",
    "password": "hey-hello"
 }
 
### DELETE USER
DELETE http://localhost:4000/api/users/6631726c93081557518a7e3b
Content-Type: application/json

### GET ALL EVENTS
GET http://localhost:4000/api/posts

### GET ONE EVENT
GET http://localhost:4000/api/posts/663870fd749549c746afc82d

### CREATE A EVENT
POST http://localhost:4000/api/posts
Content-Type: application/json

{
  "title": "Outdoor Festival - 2",
  "content": "An outdoor festival with a lot of bands",
  "author": "662f6f449436eabb4ddaf590",
  "date": "30 April",
  "place": "Kungsbacka",
  "category": "outdoor event",
  "imageId": "663aaddda5440d447cfb5387"
  
}

 
### EDIT AN EVENT
PUT http://localhost:4000/api/posts/663aadfea5440d447cfb5389
Content-Type: application/json

{
  "title": "Outdoor Festival 5",
  "content": "A outdoor festival with a lot of bands",
  "author": "6630b609d1a067de48f90498",
  "date": "30 April",
  "place": "Kungsbacka",
  "category": "outdoor event",
  "imageId": "663aaef9a5440d447cfb539c"
 

}

### DELETE AN EVENT
DELETE http://localhost:4000/api/posts/


### GET ONE IMAGE
GET http://localhost:4000/api/images/6638e22151fc497bf049e822

### UPlOAD AN IMAGE
POST http://localhost:4000/api/images/
Content-Type: multipart/form-data; boundary=FormRow

--FormRow
Content-Disposition: form-data; name="image"; filename="event.jpg"
Content-Type: image/jpeg

< ./event4.jpg
--FormRow--



