### GET ALL USERS
GET http://localhost:4000/api/users

### GET USER INFO
GET http://localhost:4000/api/users/auth

### REGISTER USER
POST http://localhost:4000/api/users/register
Content-Type: application/json

 {
    "email": "cata-8@mail.com",
    "password": "hey"
 }

### LOGIN USER
POST http://localhost:4000/api/users/login
Content-Type: application/json

 {
    "email": "cata-10@mail.com",
    "password": "hey",
    "isAdmin": true
 }

### UPDATE USER
PUT http://localhost:4000/api/users/1
Content-Type: application/json

 { 
    "id": 1,
    "email": "cata@mail.com",
    "password": "hello"
 }
 
### DELETE USER
DELETE http://localhost:4000/api/users/1
Content-Type: application/json

### GET ALL EVENTS
GET http://localhost:4000/api/events

### GET ONE EVENT
GET http://localhost:4000/api/events/1

### CREATE A EVENT
POST http://localhost:4000/api/events
Content-Type: application/json

{
  "title": "Music Festival",
  "date": "27 May",
  "place": "Kungsbacka",
  "category": "music event",
  "createBy": "user123"
}

### EDIT AN EVENT
PUT http://localhost:4000/api/events/1
Content-Type: application/json

{
  "title": "Outdoor Festival",
  "date": "30 April",
  "place": "Kungsbacka",
  "category": "outdoor event",
  "createBy": "user123"
}

### DELETE AN EVENT
DELETE http://localhost:4000/api/events/1



